### ISSUE TITLE
Can not deserialize an empty date arrray.

### ISSUE THREAD

**Issue by djseng** [windhandel/angular-http-deserializer#1]
```
class SomeDates {
    @dataType(Date, true) @converters({ 'undefined': (): Date[] => [] }) public dates: Date[];
}
  
describe('Deserialize Array of empty Dates in SomeDates', () => {
  const deSomeDates: deserializeSig<SomeDates> = deserializer<SomeDates>(SomeDates);
  const someDates = { 'dates': ['2019-03-06T00:00:00'] };
  const noDates = { 'dates': [] };

  it('should deserialize someDates', () => {
    const desSomeDates: SomeDates = deSomeDates(someDates);
    expect(desSomeDates).toBeTruthy();
    expect(desSomeDates.dates.length).toEqual(1);
    expect(desSomeDates.dates[0].toISOString()).toEqual('2019-03-06T06:00:00.000Z');
  });

  it('should deserialize noDates', () => {
    const desSomeDates: SomeDates = deSomeDates(noDates);
    expect(desSomeDates).toBeTruthy();
    expect(desSomeDates.dates.length).toEqual(0);
  });
});
```
The second test fails:
```
Chrome 72.0.3626 (Windows 10.0.0) Deserialize Array of empty Dates in SomeDates should deserialize noDates FAILED
        Error: Array deserialization error. Object must be array.
            at deserialize (src/index.ts:78:14 <- src/index.js:156:27)
            at Object.deserialize (src/index.ts:121:32 <- src/index.js:240:49)
            at UserContext.it (src/deserializer.primitive.spec.ts:139:36 <- src/deserializer.primitive.spec.js:122:30)
            at <Jasmine>
```

**Comment by djseng** [comment]
Fails regardless of the `@converter`.

**Comment by djseng** [comment]
in `index.ts` lines 77-79.

if I change
```
    if (mustBeArray && (!isArray || valueTypeString == 'undefined')) {
        throw new Error('Array deserialization error. Object must be array.');
    }
```
to
```
    if (mustBeArray && (!isArray || valueTypeString == 'undefined')) {
        return [];
    }
```

... this test passes, as well as your other defined tests.

**Comment by windhandel** [comment]
Thanks, @djseng.  I believe that was an expected negative case.  I'll try to check it out this evening and get back to you.
